version: '3.8'
services:
##########################################################
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neo.123
    ports:
      - 3306:3306
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
####################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=neo.123
      - PMA_HOST=mysql
    ports:
      - '8078:80'
    depends_on:
      - mysql
################# Keycloak CON MYSQL ########################
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloakServer
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/db_users
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: neo.123
      KC_HOSTNAME: localhost
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config_realm/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
####################################################################################
  registry-discovery:
      container_name: ms-eureka
      image: microservices/ms-eureka:0.0.1-SNAPSHOT
      ports:
        - 8761:8761
      environment:
        - JAVA_OPTS=
          -Xms256M
          -Xmx256M