version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    container_name: keycloakServer
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config_realm/:/opt/keycloak/data/import:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
##########################################################
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: neo.123
      MYSQL_DATABASE: db_inventory
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
####################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=neo.123
      - PMA_HOST=mysql
    ports:
      - '8078:80'
    depends_on:
      - mysql