
server:
  port: 8079
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: category_product_service
          uri: lb://ms-category-product
          predicates:
            - Path=/api/v1/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: AuthenticationFilter
        - id: user_service
          uri: lb://ms-users
          predicates:
            - Path=/api/user/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: AuthenticationFilter
        - id: pedidos_service
          uri: lb://ms-pedidos
          predicates:
            - Path=/api/pedido/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: AuthenticationFilter